### ISSUE TITLE
Using the before-page and after-page named slots

### ISSUE THREAD

**Issue by dnewkerk** [devstark-com/vue-layout-broker#2]
Hi, thanks for creating this plugin. I'm having difficulty understanding how to use the `before-page` and `after-page` named slots.

I was thinking that I could use these named slots from within the page component loaded by my router (e.g. IndexPage in your demo). For example I have some filter/search options on certain pages which I'd like to display in a sticky sub-header of my layout, outside of the normal content area.

However if I add `<template v-slot:before-page>...</template>` within the component, I get a compiling error: `<template v-slot> can only appear at the root level inside the receiving the component`

If I then move the template to the root level, I get a different error: `Cannot use <template> as component root element because it may contain multiple nodes.`

Anyhow, any insight would be greatly appreciated! Thank you.

**Comment by Saymon-biz** [comment]
hey @dnewkerk 

1) Regarding on how to inject some page-specific stuff into the header. Try to take a look at that https://github.com/LinusBorg/portal-vue it's a more proper way to do like that in Vue app

2) regarding the error you have experienced. Try to do it like here https://codesandbox.io/s/84x24pkn49?fontsize=14 but note that the purpose

Note that these slots are in the component for the case when you need to inject some stuff before or after the page's markup for several layouts at once and you want to do in one place. I think `portal-vue` fits your needs better
